### ISSUE TITLE
starttest do: index out of range

### ISSUE THREAD

**Issue by christophberger** [christophberger/start#7]
```
> ./starttest do
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/christophberger/start.readCommand(0xc820012ac0, 0x0, 0x0, 0xc820053df0, 0x0, 0x0)
        /Users/christoph/Development/Go/Code/src/github.com/christophberger/start/command.go:245 +0x957
github.com/christophberger/start.Up()
        /Users/christoph/Development/Go/Code/src/github.com/christophberger/start/start.go:164 +0x7e0
main.main()
        /Users/christoph/Development/Go/Code/src/github.com/christophberger/start/examples/test/starttest.go:82 +0x54c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1> 
```

**Comment by christophberger** [comment]
Fixed by commit a5bc4774f507635e339429e8ab1ec126bc125f7d.
